#!/usr/bin/env R

# this script calculates the coefficients of temperature correlations between successive years

# loading dataset
load("../data/KeyWestAnnualMeanTemperature.RData")

# plotting the time series and saving the image in a pdf format
pdf("../results/Temp_Plot.pdf", height = 4)
plot(ats$Year, ats$Temp, main = "Temperature in Key West, Florida for the 20th Century", xlab = "Years", ylab = "Temperatures", type = "b")
graphics.off()

# creating two vectors in a (n, n-1) pairing format
x_t0 = ats$Temp[-100]
x_t1 = ats$Temp[-1]

# calculating the correlation coefficient of these pairs
c1 = format(round(cor(x_t0, x_t1), 3), nsmall = 3)
print(paste("The value of the correlation coefficient is", c1), quote = FALSE)

# for loop which calculates correlation coefficients in a variable
temp_cor = rep(NA, 10000)
for(i in 1:10000){ #looping 10000 times!
    test = sample(ats$Temp, replace = FALSE) # random permutations to test for randomness
    temp_cor[i] = cor(test[-100], test[-1]) # storing the values inside a variable
}

# plotting and saving the histogram of the temperature correlation coefficients in a pdf file
pdf("../results/Temp_Hist.pdf")
hist(temp_cor, main = "Temperature Correlation", xlab = "Correlation")
abline(v = cor(x_t0, x_t1), lty = 2, col = "red")
graphics.off()

# calculating the p-value
pVal = format(length(which(temp_cor > cor(x_t0, x_t1)))/length(which(temp_cor < cor(x_t0, x_t1))), scientific = TRUE)
print(paste("The approximate p-value of the graph is", pVal), quote = FALSE)

print("To find out more about the report analysis of these results, please refer to the Autocorrelation.pdf file, which can be generated by converting the Autocorrelation.tex file into a pdf file.", quote = FALSE)
